import pandas as pd

# Data for the CSV file
data = [
    ("obvious is what is a cryptocurrency?", "What exactly is a cryptocurrency?", 1, 10.5, 5, 1, 10),
    ("So this word was kind of invented 10 years ago when, I don't know how many of you know the origin story of where Bitcoin came from, but basically a pseudonym on the internet dropped a paper and some open source code in a forum on an email list and said, hey, I have this idea for this thing called Bitcoin.", "The term was created about a decade ago when an anonymous person posted a paper and some open source code online, introducing the idea of Bitcoin.", 1, 19.5, 23, 1, 37),
    ("It's kind of like electronic cash.", "It's similar to digital money.", 1, 19.2, 5, 1, 11),
    ("Here's how I think it could work.", "This is how I think it might work.", 1, 18.0, 8, 1, 13),
    ("And here is some code if you want to run it and become part of this peer-to-peer network.", "Here's some code if you want to join the network.", 1, 19.3, 10, 1, 17),
    ("We don't know who this person is.", "We don't know who this person is.", 1, 15.5, 7, 1, 10),
    ("This person is basically virtually disappeared from the internet and from the world.", "This person has disappeared from the internet and the world.", 1, 12.8, 11, 1, 20),
    ("But it's created something that has captured so many people's imaginations and has sort of, depending on how you measure it, created billions and billions of dollars of economic value and sort of inspired a lot of people to think about how to use this technology to solve a myriad of different problems, not just electronic payments.", "But it has inspired many people and created economic value in the billions.", 1, 19.4, 14, 1, 28),
    ("So cryptocurrencies and the technology behind them are inspiring people to think about how to bank the unbanked, add more auditability and traceability to our world, get rid of trusted intermediaries and institutions in certain situations, and basically solve every problem if you read about what blockchains can do on the internet.", "Cryptocurrencies inspire solutions for banking, auditability, and problem-solving.", 1, 16.3, 11, 1, 22),
    ("Now, that's not exactly what this class is about.", "But that's not what this class is about.", 1, 18.0, 8, 1, 11),
    ("This class is going to be about technology and infrastructure.", "This class focuses on technology and infrastructure.", 1, 18.5, 6, 1, 12),
    ("You are going to learn how to create a cryptocurrency, what goes inside a cryptocurrency, what's important, what are the techniques, and what application you choose to apply that to down the line.", "You will learn to create a cryptocurrency, understand its components, techniques, and possible applications.", 1, 19.8, 17, 1, 29),
    ("That's kind of up to you.", "That is up to you.", 1, 19.7, 5, 1, 7),
    ("But we're not going to be doing digital identity or health care records or something like that.", "We won't be covering digital identity or health care records.", 1, 18.9, 9, 1, 16),
    ("We're going to be talking about the technology.", "We will discuss the technology.", 1, 19.0, 5, 1, 10),
    ("So a big question is how are cryptocurrencies different from regular currencies?", "How are cryptocurrencies different from regular currencies?", 1, 18.2, 8, 1, 17),
    ("And another thing that I want to make really clear is that the terms in this space are still being defined.", "The terms in this space are still being defined.", 1, 19.6, 9, 1, 16),
    ("So you will hear people throw around all sorts of terms, cryptocurrency, blockchain, consensus.", "You will hear many terms like cryptocurrency, blockchain, consensus.", 1, 18.4, 11, 1, 21),
    ("And these words are kind of have floating evolving meanings right now.", "These words have evolving meanings.", 1, 19.7, 5, 1, 9),
    ("Part of that is because Bitcoin, the first cryptocurrency, didn't come from academia as far as we know.", "Bitcoin did not come from academia but from internet enthusiasts.", 1, 19.1, 10, 1, 20),
    ("It came from a community of enthusiasts on the internet.", "It came from internet enthusiasts.", 1, 17.8, 5, 1, 10),
    ("And so it doesn't necessarily have the same basis and rigor that we might expect for most of our academic fields of study.", "So, it lacks the academic rigor.", 1, 15.5, 7, 1, 14),
    ("It's totally OK. We're figuring it out as we go along.", "It's OK. We're figuring it out.", 1, 18.7, 6, 2, 9),
    ("And academia is really embracing this topic.", "Academia is embracing this topic.", 1, 19.0, 5, 1, 13),
    ("So if any of you are graduate students who are looking for an area in which to do research, I think basically the number of papers published on cryptocurrencies and blockchain technology in respected academic venues is doubling every year.", "Graduate students can find research opportunities.", 1, 19.1, 7, 1, 18),
    ("So there's huge opportunity here.", "Papers on cryptocurrencies double every year.", 1, 18.6, 6, 1, 13),
    ("So cryptocurrencies are not regular currencies.", "Cryptocurrencies are not regular currencies.", 1, 19.4, 5, 1, 11),
    ("They're not a dollar or a pound or a euro, what we normally think of as currency.", "They are not dollars, pounds, or euros.", 1, 18.2, 7, 1, 14),
    ("There's something different.", "They are different.", 1, 18.7, 3, 1, 5),
    ("Bitcoin was sort of created out of nowhere.", "Bitcoin was created from nothing.", 1, 19.6, 5, 1, 10),
    ("It's kind of like electronic cash.", "It's like digital money.", 2, 24.2, 4, 1, 8),
    ("Here's how I think it could work.", "This is how I think it works.", 2, 25.3, 7, 1, 11),
    ("And here is some code if you want to run it and become part of this peer-to-peer network.", "Here's some code if you want to join the network.", 2, 27.4, 9, 1, 15),
    ("We don't know who this person is.", "We don't know who this person is.", 2, 22.6, 6, 1, 9),
    ("This person is basically virtually disappeared from the internet and from the world.", "This person has vanished from the internet and the world.", 2, 23.5, 10, 1, 18),
    ("But it's created something that has captured so many people's imaginations and has sort of, depending on how you measure it, created billions and billions of dollars of economic value and sort of inspired a lot of people to think about how to use this technology to solve a myriad of different problems, not just electronic payments.", "But it has inspired many people and created economic value in billions.", 2, 26.7, 13, 1, 26),
    ("So cryptocurrencies and the technology behind them are inspiring people to think about how to bank the unbanked, add more auditability and traceability to our world, get rid of trusted intermediaries and institutions in certain situations, and basically solve every problem if you read about what blockchains can do on the internet.", "Cryptocurrencies inspire solutions for banking and auditability.", 2, 28.3, 7, 1, 14),
    ("Now, that's not exactly what this class is about.", "But this class isn't about that.", 2, 29.4, 5, 1, 9),
    ("This class is going to be about technology and infrastructure.", "This class focuses on tech and infrastructure.", 2, 22.5, 6, 1, 11),
    ("You are going to learn how to create a cryptocurrency, what goes inside a cryptocurrency, what's important, what are the techniques, and what application you choose to apply that to down the line.", "You will learn to create a cryptocurrency and understand its components, techniques, and applications.", 2, 23.4, 15, 1, 27),
    ("That's kind of up to you.", "That is up to you.", 2, 24.3, 5, 1, 7),
    ("But we're not going to be doing digital identity or health care records or something like that.", "We won't cover digital identity or health care records.", 2, 26.1, 8, 1, 14),
    ("We're going to be talking about the technology.", "We will discuss the tech.", 2, 27.4, 5, 1, 8),
    ("So a big question is how are cryptocurrencies different from regular currencies?", "How are cryptocurrencies different from regular money?", 2, 25.8, 7, 1, 15),
    ("And another thing that I want to make really clear is that the terms in this space are still being defined.", "The terms in this space are still being defined.", 2, 27.7, 8, 1, 14),
    ("So you will hear people throw around all sorts of terms, cryptocurrency, blockchain, consensus.", "You will hear terms like cryptocurrency, blockchain, consensus.", 2, 28.9, 9, 1, 17),
    ("And these words are kind of have floating evolving meanings right now.", "These words have evolving meanings.", 2, 29.8, 5, 1, 9),
    ("Part of that is because Bitcoin, the first cryptocurrency, didn't come from academia as far as we know.", "Bitcoin did not come from academia but from internet enthusiasts.", 2, 28.3, 9, 1, 18),
    ("It came from a community of enthusiasts on the internet.", "It came from enthusiasts online.", 2, 23.4, 5, 1, 10),
    ("And so it doesn't necessarily have the same basis and rigor that we might expect for most of our academic fields of study.", "It lacks the rigor of academia.", 2, 24.1, 6, 1, 12),
    ("It's totally OK. We're figuring it out as we go along.", "It's OK. We are figuring it out.", 2, 26.7, 6, 2, 9),
    ("And academia is really embracing this topic.", "Academia is embracing this topic.", 2, 25.3, 5, 1, 10),
    ("So if any of you are graduate students who are looking for an area in which to do research, I think basically the number of papers published on cryptocurrencies and blockchain technology in respected academic venues is doubling every year.", "Graduate students can find research opportunities.", 2, 24.8, 6, 1, 16),
    ("So there's huge opportunity here.", "Papers on cryptocurrencies double yearly.", 2, 27.1, 5, 1, 12),
    ("So cryptocurrencies are not regular currencies.", "Cryptocurrencies are not regular currencies.", 2, 28.6, 5, 1, 11),
    ("They're not a dollar or a pound or a euro, what we normally think of as currency.", "They are not dollars, pounds, or euros.", 2, 27.4, 6, 1, 13),
    ("There's something different.", "They are different.", 2, 29.5, 3, 1, 5),
    ("Bitcoin was sort of created out of nowhere.", "Bitcoin was created from nothing.", 2, 28.3, 5, 1, 10),
    ("It's kind of like electronic cash.", "It's like digital money.", 3, 33.8, 4, 1, 7),
    ("Here's how I think it could work.", "This is how I think it works.", 3, 34.2, 7, 1, 11),
    ("And here is some code if you want to run it and become part of this peer-to-peer network.", "Here's code if you want to join the network.", 3, 38.1, 8, 1, 13),
    ("We don't know who this person is.", "We don't know who this person is.", 3, 32.0, 6, 1, 9),
    ("This person is basically virtually disappeared from the internet and from the world.", "This person has vanished from the internet.", 3, 37.4, 7, 1, 14),
    ("But it's created something that has captured so many people's imaginations and has sort of, depending on how you measure it, created billions and billions of dollars of economic value and sort of inspired a lot of people to think about how to use this technology to solve a myriad of different problems, not just electronic payments.", "But it has inspired many people and created value in billions.", 3, 35.2, 11, 1, 22),
    ("So cryptocurrencies and the technology behind them are inspiring people to think about how to bank the unbanked, add more auditability and traceability to our world, get rid of trusted intermediaries and institutions in certain situations, and basically solve every problem if you read about what blockchains can do on the internet.", "Cryptocurrencies inspire banking and auditability solutions.", 3, 37.5, 6, 1, 13),
    ("Now, that's not exactly what this class is about.", "But this class isn't about that.", 3, 39.6, 5, 1, 9),
    ("This class is going to be about technology and infrastructure.", "This class is about tech and infrastructure.", 3, 32.6, 6, 1, 11),
    ("You are going to learn how to create a cryptocurrency, what goes inside a cryptocurrency, what's important, what are the techniques, and what application you choose to apply that to down the line.", "You will learn to create a cryptocurrency and understand its components, techniques, and applications.", 3, 33.7, 14, 1, 25),
    ("That's kind of up to you.", "That is up to you.", 3, 34.2, 5, 1, 7),
    ("But we're not going to be doing digital identity or health care records or something like that.", "We won't cover digital identity or health records.", 3, 35.9, 7, 1, 12),
    ("We're going to be talking about the technology.", "We will discuss the tech.", 3, 36.7, 5, 1, 8),
    ("So a big question is how are cryptocurrencies different from regular currencies?", "How are cryptocurrencies different from regular money?", 3, 37.4, 7, 1, 15),
    ("And another thing that I want to make really clear is that the terms in this space are still being defined.", "The terms in this space are still being defined.", 3, 38.1, 8, 1, 14),
    ("So you will hear people throw around all sorts of terms, cryptocurrency, blockchain, consensus.", "You will hear terms like cryptocurrency, blockchain, and consensus.", 3, 39.2, 9, 1, 17),
    ("And these words are kind of have floating evolving meanings right now.", "These words have evolving meanings.", 3, 38.7, 5, 1, 9),
    ("Part of that is because Bitcoin, the first cryptocurrency, didn't come from academia as far as we know.", "Bitcoin did not come from academia but from internet enthusiasts.", 3, 38.9, 9, 1, 18),
    ("It came from a community of enthusiasts on the internet.", "It came from enthusiasts online.", 3, 32.1, 5, 1, 9),
    ("And so it doesn't necessarily have the same basis and rigor that we might expect for most of our academic fields of study.", "It lacks academic rigor.", 3, 33.5, 4, 1, 9),
    ("It's totally OK. We're figuring it out as we go along.", "It's OK. We're figuring it out.", 3, 35.7, 6, 2, 9),
    ("And academia is really embracing this topic.", "Academia embraces this topic.", 3, 34.6, 4, 1, 9),
    ("So if any of you are graduate students who are looking for an area in which to do research, I think basically the number of papers published on cryptocurrencies and blockchain technology in respected academic venues is doubling every year.", "Grad students can find research chances.", 3, 36.4, 6, 1, 14),
    ("So there's huge opportunity here.", "Papers on cryptocurrencies double yearly.", 3, 35.1, 5, 1, 12),
    ("So cryptocurrencies are not regular currencies.", "Cryptocurrencies aren't regular currencies.", 3, 36.7, 5, 1, 10),
    ("They're not a dollar or a pound or a euro, what we normally think of as currency.", "They aren't dollars, pounds, or euros.", 3, 37.9, 5, 1, 10),
    ("There's something different.", "They are different.", 3, 38.8, 3, 1, 5),
    ("Bitcoin was sort of created out of nowhere.", "Bitcoin was created from nowhere.", 3, 39.1, 5, 1, 10),
    ("It's kind of like electronic cash.", "It's like electronic money.", 4, 42.3, 4, 1, 8),
    ("Here's how I think it could work.", "This is how I think it works.", 4, 45.3, 7, 1, 11),
    ("And here is some code if you want to run it and become part of this peer-to-peer network.", "Here's some code if you want to join the network.", 4, 47.1, 9, 1, 15),
    ("We don't know who this person is.", "We don't know who this person is.", 4, 42.6, 6, 1, 9),
    ("This person is basically virtually disappeared from the internet and from the world.", "This person has vanished from the internet and the world.", 4, 44.8, 9, 1, 17),
    ("But it's created something that has captured so many people's imaginations and has sort of, depending on how you measure it, created billions and billions of dollars of economic value and sort of inspired a lot of people to think about how to use this technology to solve a myriad of different problems, not just electronic payments.", "But it has inspired many people and created billions in value.", 4, 45.1, 10, 1, 21),
    ("So cryptocurrencies and the technology behind them are inspiring people to think about how to bank the unbanked, add more auditability and traceability to our world, get rid of trusted intermediaries and institutions in certain situations, and basically solve every problem if you read about what blockchains can do on the internet.", "Cryptocurrencies inspire banking and auditability solutions.", 4, 48.3, 6, 1, 13),
    ("Now, that's not exactly what this class is about.", "But this class isn't about that.", 4, 49.6, 5, 1, 9),
    ("This class is going to be about technology and infrastructure.", "This class focuses on tech and infrastructure.", 4, 42.6, 6, 1, 11),
    ("You are going to learn how to create a cryptocurrency, what goes inside a cryptocurrency, what's important, what are the techniques, and what application you choose to apply that to down the line.", "You will learn how to create a cryptocurrency and understand its components, techniques, and applications.", 4, 43.5, 13, 1, 23),
    ("That's kind of up to you.", "That is up to you.", 4, 42.8, 5, 1, 7),
    ("But we're not going to be doing digital identity or health care records or something like that.", "We won't cover digital identity or health records.", 4, 44.3, 7, 1, 12),
    ("We're going to be talking about the technology.", "We will discuss the tech.", 4, 45.7, 5, 1, 8),
    ("So a big question is how are cryptocurrencies different from regular currencies?", "How are cryptocurrencies different from regular money?", 4, 44.3, 7, 1, 15),
    ("And another thing that I want to make really clear is that the terms in this space are still being defined.", "The terms in this space are still being defined.", 4, 45.6, 8, 1, 14),
    ("So you will hear people throw around all sorts of terms, cryptocurrency, blockchain, consensus.", "You will hear terms like cryptocurrency, blockchain, and consensus.", 4, 46.3, 9, 1, 17),
    ("And these words are kind of have floating evolving meanings right now.", "These words have evolving meanings.", 4, 48.4, 5, 1, 9),
    ("Part of that is because Bitcoin, the first cryptocurrency, didn't come from academia as far as we know.", "Bitcoin did not come from academia but from internet enthusiasts.", 4, 47.9, 9, 1, 18),
    ("It came from a community of enthusiasts on the internet.", "It came from online enthusiasts.", 4, 42.1, 5, 1, 9),
    ("And so it doesn't necessarily have the same basis and rigor that we might expect for most of our academic fields of study.", "It lacks academic rigor.", 4, 43.5, 4, 1, 9),
    ("It's totally OK. We're figuring it out as we go along.", "It's OK. We're figuring it out.", 4, 45.7, 6, 2, 9),
    ("And academia is really embracing this topic.", "Academia embraces this topic.", 4, 44.6, 4, 1, 9),
    ("So if any of you are graduate students who are looking for an area in which to do research, I think basically the number of papers published on cryptocurrencies and blockchain technology in respected academic venues is doubling every year.", "Grad students can find research chances.", 4, 46.4, 6, 1, 14),
    ("So there's huge opportunity here.", "Papers on cryptocurrencies double yearly.", 4, 45.1, 5, 1, 12),
    ("So cryptocurrencies are not regular currencies.", "Cryptocurrencies aren't regular currencies.", 4, 46.7, 5, 1, 10),
    ("They're not a dollar or a pound or a euro, what we normally think of as currency.", "They aren't dollars, pounds, or euros.", 4, 47.9, 5, 1, 10),
    ("There's something different.", "They are different.", 4, 48.8, 3, 1, 5),
    ("Bitcoin was sort of created out of nowhere.", "Bitcoin was created from nowhere.", 4, 49.1, 5, 1, 10),
    ("It's kind of like electronic cash.", "It's like electronic money.", 5, 52.8, 4, 1, 8),
    ("Here's how I think it could work.", "This is how I think it works.", 5, 54.5, 7, 1, 11),
    ("And here is some code if you want to run it and become part of this peer-to-peer network.", "Here's some code if you want to join the network.", 5, 55.4, 9, 1, 15),
    ("We don't know who this person is.", "We don't know who this person is.", 5, 52.4, 6, 1, 9),
    ("This person is basically virtually disappeared from the internet and from the world.", "This person has vanished from the internet and the world.", 5, 55.7, 9, 1, 17),
    ("But it's created something that has captured so many people's imaginations and has sort of, depending on how you measure it, created billions and billions of dollars of economic value and sort of inspired a lot of people to think about how to use this technology to solve a myriad of different problems, not just electronic payments.", "But it has inspired many people and created billions in value.", 5, 54.2, 10, 1, 21),
    ("So cryptocurrencies and the technology behind them are inspiring people to think about how to bank the unbanked, add more auditability and traceability to our world, get rid of trusted intermediaries and institutions in certain situations, and basically solve every problem if you read about what blockchains can do on the internet.", "Cryptocurrencies inspire banking and auditability solutions.", 5, 57.3, 6, 1, 13),
    ("Now, that's not exactly what this class is about.", "But this class isn't about that.", 5, 58.4, 5, 1, 9),
    ("This class is going to be about technology and infrastructure.", "This class focuses on tech and infrastructure.", 5, 52.6, 6, 1, 11),
    ("You are going to learn how to create a cryptocurrency, what goes inside a cryptocurrency, what's important, what are the techniques, and what application you choose to apply that to down the line.", "You will learn how to create a cryptocurrency and understand its components, techniques, and applications.", 5, 52.5, 13, 1, 23),
    ("That's kind of up to you.", "That is up to you.", 5, 51.6, 5, 1, 7),
    ("But we're not going to be doing digital identity or health care records or something like that.", "We won't cover digital identity or health records.", 5, 55.1, 7, 1, 12),
    ("We're going to be talking about the technology.", "We will discuss the tech.", 5, 54.8, 5, 1, 8),
    ("So a big question is how are cryptocurrencies different from regular currencies?", "How are cryptocurrencies different from regular money?", 5, 53.8, 7, 1, 15),
]